In [1]:
#1 ...
import numpy as np
a = np.arange(12)
a = a.reshape(3,2,2)
print(a)
a[...,0]                                  #1) same as a[:,:,0]


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

* same as a[:,:,0]
* print the elements of zero column index.


In [2]:
#2
a = np.array([[0, 1, 2, 3, 4],
           [10,11,12,13,14],
           [20,21,22,23,24],                                                    
           [30,31,32,33,34]])
print(a) 
print(a[0,0])
print(a[-1])                  # last row
print(a[1:3,1:4])             # subarray

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]
0
[30 31 32 33 34]
[[11 12 13]
 [21 22 23]]


* indexing or selector of required elements

In [3]:
#3
abs(-1)
abs(np.array([-1.2, 1.2]))
abs(1.2+1j)

1.5620499351813308

* abs() returns the absolute magnitude or value of the argument
* int or float - absolute magnitude 
* Complex - Root over a square + b square

In [4]:
#4
np.add.accumulate(np.array([1.,2.,3.,4.]))
np.array([1., 1.+2., (1.+2.)+3., ((1.+2.)+3.)+4.])
np.multiply.accumulate(np.array([1.,2.,3.,4.]))
np.add.accumulate(np.array([[1,2,3],[4,5,6]]), axis = 1)


array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

* it makes an iterator that returns accumulated sum or accumulated Results of the Other binary functions which is mentioned in function parameter
* this is same as np.cumsum(cummalative sum)
* axis=1 refers to a columns(changes happens column-wise)



In [5]:
#5
np.add(np.array([-1.2, 1.2]), np.array([1,3]))

array([-0.2,  4.2])

* addition or adding to two arrays, element wise

In [6]:
#6 - all()
a = np.array([True, False, True])
a.all()

False

In [7]:
a = np.array([1,2,3])
all(a > 0)

True

* all() function returns a Boolean value if only condition of all the elements of an array are true then it returns true otherwise false

In [8]:
#8 - alltrue()
b = np.array([True, False, True, True])
np.alltrue(b)

False

* returns true when all the elements of the array evaluates true

In [9]:
#9 -np.angle()

print(np.angle(1+1j))                           # in radians
print(np.angle(1+1j,deg=True))                  # in degrees
print(np.angle(3))

0.7853981633974483
45.0
0.0


* returns the angle value of a complex number by default radian

In [10]:
#10 - any()
a = np.array([True, False, True])
a.any()                                       # gives True if at least 1 element of a is True, otherwise False

True

* returns true if at least one element in array is true

In [11]:
#11 - append()
a = np.array([10,20,30,40])
np.append(a,50)

array([10, 20, 30, 40, 50])

In [12]:
np.array([10, 20, 30, 40, 50])
np.append(a,(50,60))

array([10, 20, 30, 40, 50, 60])

* add the elements to end of the array. elements can be list tuple any data type

In [13]:
#12 - apply_over_axes()
a = np.arange(20).reshape(2,5,2)                             # a has 3 axes: 0,1 and 2
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [14]:
np.sum(a,axis=(0,2))

array([22, 30, 38, 46, 54])

In [15]:
np.apply_over_axes(np.sum, a, [2,0])                # sum over all axes except axis=1, result has same shape as original


array([[[22],
        [30],
        [38],
        [46],
        [54]]])

* applies a function repeatedly over multiple axis in a array, the dimension of the output array is same as the input,but shape might be different

In [16]:
#13 = arange()
np.arange(20)
np.arange(20,50)
#np.arange(20,50,3)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

* Returns all the values within the given range or interval

In [17]:
#14 - arccos()
np.arccos(np.array([-1, 1]))

array([3.14159265, 0.        ])

* return the inverse cosine, elementwise
* The function accepts both real and complex inputs. For real values of X in the interval [-1, 1], acos(X) returns values in     the interval [0, π].

In [18]:
#15 - arccosh()
np.arccosh(np.array([5, 10.0]))

array([2.29243167, 2.99322285])

* return the inverse hyperbolic cosine elementwise

In [19]:
#16 - arcsin()
np.arcsin(np.array([0, 1]))

array([0.        , 1.57079633])

* return the inverse sine, elementwise

In [20]:
#19 - arctan2()
np.arctan2(np.array([0, 1]), np.array([1, 0]))

array([0.        , 1.57079633])

* element wise arctangent of X1/X2 choosing the quadrant correctly

In [21]:
#20 - arctanh()
np.arctanh(np.array([0, -0.5]))

array([ 0.        , -0.54930614])

* return the inverse hyperbolic tan, elementwise

In [22]:
#21 - argmax()
a = np.array([10,20,30])
maxindex = a.argmax()
a[maxindex]

30

In [23]:
a = np.array([[10,50,30],[60,20,40]])
maxindex = a.argmax()
maxindex
#a

3

In [24]:
 a.argmax(axis=0)                               # for each column: the row index of the maximum value

array([1, 0, 1], dtype=int64)

In [25]:
a.argmax(axis=1)                                  # for each row: the column index of the maximum value

array([1, 0], dtype=int64)

* returns the maximum value along the given axis

In [26]:
#22 - argmin()
a = np.array([10,20,30])
minindex = a.argmin()
a[minindex]

10

In [27]:
a = np.array([[10,50,30],[60,20,40]])
minindex = a.argmin()
minindex
a

array([[10, 50, 30],
       [60, 20, 40]])

In [28]:
a.argmin(axis=0)                                 # for each column: the row index of the minimum value

array([0, 1, 0], dtype=int64)

* returns the minimum value along the given axis

In [29]:
#23 - argsort()
a = np.array([2,0,8,4,1,9])
ind = a.argsort()                                  # indices of sorted array using quicksort (default)
ind

array([1, 4, 0, 3, 2, 5], dtype=int64)

In [30]:
ind = a.argsort(kind='merge')                         # algorithm options are 'quicksort', 'mergesort' and 'heapsort'
a = np.array([[8,4,1],[2,0,9]])
a

array([[8, 4, 1],
       [2, 0, 9]])

In [31]:
ind = a.argsort(axis=0)                          # sorts on columns. NOT the same as a.sort(axis=1)
ind

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [32]:
ind = a.argsort(axis=1)                                  # sort along rows. Can use a.argsort(axis=-1) for last axis.
ind

array([[2, 1, 0],
       [1, 0, 2]], dtype=int64)

* returns the index of Array in sorted manner

In [33]:
#24 -array(
np.array([1,2,3])                       # conversion from a list to an array

array([1, 2, 3])

* creates an array

In [34]:
#25 - array_split
a = np.array([[1,2,3,4],[5,6,7,8]])
np.array_split(a,2,axis=0)                                       # split a in 2 parts. row-wise

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

* split an array into multiple arrays

In [35]:
#26 - asarray()
m = np.matrix('1 2; 5 8')
m


matrix([[1, 2],
        [5, 8]])

In [36]:
a = np.asarray(m)                           # a is array type with same contents as m -- data is not copied
a

array([[1, 2],
       [5, 8]])

* converts input(any data structure) into array

In [37]:
#27 asanyarray()
np.asanyarray(m)

matrix([[1, 2],
        [5, 8]])

In [38]:
a=[1,2,3]
np.asanyarray(a)

array([1, 2, 3])

* convert non array form to array form

In [39]:
#28 - asmatrix
a = np.array([[1,2],[5,8]])
a

array([[1, 2],
       [5, 8]])

In [40]:
m = np.asmatrix(a)                                # m is matrix type with same contents as a -- data is not copied
m

matrix([[1, 2],
        [5, 8]])

In [41]:
a=[1,2,3]
np.asmatrix(a)

matrix([[1, 2, 3]])

* converts input(any data structure) into matrixs

In [42]:
#29 - astype
x = np.array([1,2,3])
y = x.astype(np.str)                                   # convert from int32 to string
type(y[0])
print(y)     
x.astype(str)                                       # None implies converting to the default (float64)

['1' '2' '3']


C:\Users\DELL\AppData\Local\Temp\ipykernel_5364\3254327192.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = x.astype(np.str)                                   # convert from int32 to string


array(['1', '2', '3'], dtype='<U11')

* copy of the array and convert to a specified type default = float

In [43]:
#30,31,32 - atleast_1d, atleast_2d, atleast_3d
a = [1,2,3]                                                 # 0-d array
b = np.array([2,3])                                    # 1-d array
c = np.array([[4,5],[6,7]])                           # 2-d array
d = np.arange(8).reshape(2,2,2)                       # 3-d array
d
type(a)

list

In [44]:
np.atleast_3d(a,b,c,d)                                       # all output arrays have dim >= 1

[array([[[1],
         [2],
         [3]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

* convert input to array with at least one dimension, two dimension ,three dimension

In [45]:
#33 - average
a = np.array([1,2,3,4,5])
w = np.array([0.1, 0.2, 0.5, 0.2, 0.2])                   # weights, not necessarily normalized
print(np.average(w))                                            # plain mean value
np.average(a,weights=w)                                      # weighted average

0.24


3.1666666666666665

* returns weighted average along axis
* avg = sum(a*weights)/weights

In [46]:
#34 -beta
np.random.beta(a=1,b=5,size=(2,2))                               # Beta distribution alpha=1, beta=10

array([[0.06496723, 0.12938435],
       [0.04132258, 0.10398167]])

* draw samples from a beta distribution

In [47]:
#35 - binary_repr
a = 25
np.binary_repr(a)                                        # binary representation of 25

'11001'

* returns the binary representation of the input in the form of a string

In [48]:
#36 - bincount
a = np.array([2,2,4,4,5,6,6,6,1,1,1,1])              
print(np.bincount(a))                         # 0 occurs 0 times, 1 occurs 4 times, 2 occurs twice, 3 occurs 0 times, ...


[0 4 2 0 2 1 3]


In [49]:
a = np.array([5,4,4,2,2])
w = np.array([0.1, 0.2, 0.1, 0.3, 0.5])
np.bincount(a,weights=w)                      # 0 & 1 don't occur, 2 occurs twice, 3 doesn't occur, 4 occurs twice, 5 once

array([0. , 0. , 0.8, 0. , 0.3, 0.1])

* returns the number of occurrences or frequencies of all elements in an array or input, starts from 0 to given range.
* input is always int

In [50]:
#37 - binomial
np.random.binomial(n=100,p=0.5,size=(2,3))                   # binomial distribution n trials, p= success probability

array([[53, 54, 48],
       [43, 48, 51]])

* draw samples from Binomial Distribution 
* Binomial Distribution is a discrete distribution which expresses the probability of a given number of successes of n      independent experiments with known probability of success in each trial.
* the difference between normal distribution and Binomial Distribution is continuous values and Binomial have discrete distribution
* n=number of trials
* p=probability of success on each trial




In [51]:
#38 - bitwise_and
np.bitwise_and(np.array([2,5,5]), np.array([4,4,4]))

array([0, 4, 4], dtype=int32)

* return the values of bitwise and of two arrays element wise

In [52]:
#39 -bitwise_or
np.bitwise_or(np.array([2,5,5]), np.array([4,4,4]))

array([6, 5, 5], dtype=int32)

* return the values ofbitwise_or of two arrays element wise

In [53]:
#40- bitwise_xor                                                                        #both not 1 or both not 0
np.bitwise_xor(np.array([2,5,5]), np.array([4,4,4]))

array([6, 1, 1], dtype=int32)

* return the values of bitwise_xor of two arrays element wise

In [54]:
#41  - bmat
a = np.mat('1 2; 3 4')
b = np.mat('5 6; 7 8')
np.bmat('a b; b a')                            # all elements must be existing symbols

matrix([[1, 2, 5, 6],
        [3, 4, 7, 8],
        [5, 6, 1, 2],
        [7, 8, 3, 4]])

* create some metric object from a string of a given sequence---2D

In [55]:
#42 - broadcast
a = np.array([[[1,2],[3,4],[4,5]]])
b = np.array([5,6])
c = np.broadcast(a,b)
c.nd

3

* describe how numpy treats array with different shapes during automatic operation---1D,2D,3D

In [56]:
c.size                                           # number of elements along axis

6

In [57]:
#43 - bytes

print(np.random.bytes(5))                          # string of 5 random bytes

b'j\xc4\x07y\xf8'


* convert an object to an immutable byte presented object of given size and data

In [58]:
#44 - c_[]
print(np.c_[1:5])                                      # for single ranges, c_ works like r_
print(np.c_[1:5,2:6])                                  # for comma separated values, c_ stacks column-wise


[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]


* create a metric between the given range

In [59]:
#45 - cast[]()
x = np.arange(3)
print(x.dtype)
y=np.cast['int64'](x)
print(y)
z=np.cast['uint'](x)
z

int32
[0 1 2]


array([0, 1, 2], dtype=uint32)

* casting or converting input to a required specified dtype


In [60]:
#46 - ceil()
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])
np.ceil(a)                                                   # nearest integers greater-than or equal to a

array([-1., -1., -0.,  1.,  2.,  2.])

* compute smaller integer that is greater than or equal to a

In [61]:
#47 - clip
a = np.array([5,15,25,3,13])
a.clip(min=10,max=20)                                # value<10 = 10 and value>20 = 20

array([10, 15, 20, 10, 13])

* returns an array within the given limit (min, Max)
* all the values less than 10 is 10
* all the values more than 20 is 20

In [62]:
#48 - column_stack
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
np.column_stack((a,b,c))                            # a,b,c are 1-d arrays with equal length

array([[1, 3, 5],
       [2, 4, 6]])

* converts one dimensional array column into two dimensional

In [63]:
#49 - compress
a = np.array([25, 20, 30, 40])
condition = (a > 15) & (a < 35)
print(condition)
print(a.compress(condition))

[ True  True  True False]
[25 20 30]


* it will compress or remove the elements which returns false in the array and execute or returns the values which are true

In [64]:
#50 - concatenate
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.concatenate((x,y))                                       # default is axis=0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

* joining of arrays along the given axis--default= axis=0

In [65]:
#51 - conj
a = np.array([1+2j,3-4j])
a.conj()                                                   # .conj() and .conjugate() are the same

array([1.-2.j, 3.+4.j])

* the conjugate of a complex number is obtained by changing the sign of its imaginary part


In [66]:
#52 - copy

a = np.array([1,2,3])
print(a)

b = a                                                   # b is a reference to a
b[1] = 4
print(a)

a = np.array([1,2,3])
b = a.copy()                                             # b is now an independent copy of a
b[1] = 4
print(a)
print(b)

[1 2 3]
[1 4 3]
[1 2 3]
[1 4 3]


* returns a copy of array

In [67]:
#53 - corrcoef
T = np.array([1.3, 4.5, 2.8, 3.9])                     # temperature measurements
P = np.array([2.7, 8.7, 4.7, 8.2])                     # corresponding pressure measurements
print(np.corrcoef([T,P]))                              # correlation matrix of temperature and pressure

[[1.         0.98062258]
 [0.98062258 1.        ]]


* returns a pearson product correlation coefficient 

In [68]:
#54 - cos()
np.cos(np.array([0,180]))


array([ 1.        , -0.59846007])

* Returns the cosine of value passed as argument.
* returns a numeric value between -1 and 1, which represents the cosine of the angle.

In [69]:
#55 - cov()
x = np.array([1., 3., 8., 9.])
variance = np.cov(x)                                 # normalized by N-1
variance = np.cov(x, bias=1)                         # normalized by N


T = np.array([1.3, 4.5, 2.8, 3.9])                     # temperature measurements
P = np.array([2.7, 8.7, 4.7, 8.2])                     # corresponding pressure measurements
print(np.cov(T,P))                                     # covariance between temperature and pressure

[[1.97583333 3.95416667]
 [3.95416667 8.22916667]]


* Covariance indicates the level to which two variables vary together.
* that means return a matrix of relation between T and P 

In [70]:
#56 - cross()
x = np.array([1,2,3])
y = np.array([4,5,6])
np.cross(x,y)                                        # vector cross-product

array([-3,  6, -3])

* return the cross product of two arrary/matrix

In [71]:
#57 - cumprod()
a = np.array([1,2,3])
np.cumprod(a)                                        # total product 1*2*3 = 6, and intermediate results 1, 1*2

array([1, 2, 6], dtype=int32)

In [72]:
a = np.array([[1,2,3],[4,5,6]])
np.cumprod(a,dtype=float,axis=1)                      # specify type of output

array([[  1.,   2.,   6.],
       [  4.,  20., 120.]])

* Return the cumulative product of elements along a given axis.


In [73]:
#58 - cumsum()
a = np.array([1,2,3])                                   # cumulative sum = intermediate summing results & total sum
np.cumsum(a)

array([1, 3, 6], dtype=int32)

* Return the cumulative sum of elements along a given axis.

In [74]:
#59 - delete()
a = np.array([0, 10, 20, 30, 40])
np.delete(a, [2,4])                                            # remove a[2] and a[4]


array([ 0, 10, 30])

* returns an array with remaining elements after deleting.

In [75]:
#60 - det()
A = np.array([[1., 2.],[3., 4.]])
np.linalg.det(A)                                            # determinant of square matrix

-2.0000000000000004

* return the determinant of the matrics

In [76]:
#61 - diag()
a = np.arange(12).reshape(4,3)
print(a)
print(np.diag(a,k=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 4 8]


* Extract a diagonal or construct a diagonal array.
* The default k is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

In [77]:
#62 - diagflat()
x = np.array([[5,6,2],[7,8,9]])
np.diagflat(x)                                 # flatten x, then put elements on diagonal

array([[5, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 9]])

* Create a two-dimensional array with input elements as a diagonal.


In [78]:
#62 - diagonal()
a = np.arange(15).reshape(5,3)
print(a)
np.diagonal(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([0, 4, 8])

* Return specified diagonals -- always k=0.


In [79]:
#63 - diff()
x = np.array([0,1,3,9,5,10])
np.diff(x)                                                    # 1st-order differences between the elements of x


array([ 1,  2,  6, -4,  5])

In [80]:
np.diff(x,n=2)                                             # 2nd-order differences, equivalent to diff(diff(x))

array([  1,   4, -10,   9])

* used to compute the nth difference along the given axis of an input array.
* o/p = x[i+1] - x[i]

In [81]:
#64 - digitize()
x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])                            # monotonically increasing
d = np.digitize(x,bins)                                               # in which bin falls each value of x?
d


array([1, 4, 3, 2], dtype=int64)

* Return the indices of the bins to which each value in input array belongs

In [82]:
#65 - dot()
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4],[5,6]])
np.dot(x,y)                                         # matrix multiplication (2,3) x (3,2) -> (2,2)

array([[22, 28],
       [49, 64]])

* Dot product of two arrays

In [83]:
#65 - dsplit
a = np.array([[1,2],[3,4]])
b = np.dstack((a,a,a,a,a,a))                                      # stacking in depth: for k in (0,..,3): b[:,:,k] = a

c = np.dsplit(b,6)                                     # split, depth-wise, in 2 equal parts
print(c[0].shape, c[1].shape)                           # for k in (0,1): c[0][:,:,k] = a and c[1][:,:,k] = a

(2, 2, 1) (2, 2, 1)


* Split array into multiple sub-arrays along the 3rd axis(z=axis) (depth).
* dsplit() only works on arrays of 3-D or more dimensions.
* Splits an array into multiple sub-arrays of equal size

In [84]:
#66 - dstack()
a = np.array([[1,2,5],[3,4,6]])                   # shapes of a and b can only differ in the 3rd dimension (if present)
b = np.array([[5,6,3],[7,8,7]])
np.dstack((a,b))                          # stack arrays along a third axis (depth wise)

array([[[1, 5],
        [2, 6],
        [5, 3]],

       [[3, 7],
        [4, 8],
        [6, 7]]])

* stack or arrange the given arrays in a sequence depth wise (that is, along the third axis), thereby creating an array of at least 3-D .

In [85]:
#67 - dtype()
np.dtype('int16')                              # using array-scalar type
np.dtype([('f1', 'int64')])                    # record, 1 field named 'f1', containing int16

dtype([('f1', '<i8')])

* This means it gives us information about: Type of the data (integer, float, Python object, etc.) Size of the data (number of bytes)

In [86]:
#68 - empty()
print(np.empty(3))                                       # uninitialized array, size=3, dtype = float
np.empty((2,3),int)                                 # uninitialized array, dtype = int

[0. 0. 0.]


array([[0, 0, 0],
       [0, 0, 0]])

* return new array of a given shape and type. It has random values and uninitialized entries.

In [87]:
#68 - empty_like
a = np.array([[1,2,3],[4,5,6]])
np.empty_like(a,float)                              # uninitialized array with the same shape and datatype as 'a'

array([[0.00e+000, 3.46e-323, 6.92e-323],
       [1.04e-322, 1.38e-322, 1.73e-322]])

* Return a new array with the same shape and type as a given array. It has random values and uninitialized entries.


In [88]:
#69 - expand_dims
x = np.array([[1,2],[3,4]])
np.expand_dims(x,axis=0)                       # Equivalent to x[newaxis,:] or x[None] or x[newaxis]


array([[[1, 2],
        [3, 4]]])

In [89]:
np.expand_dims(x,axis=1)

array([[[1, 2]],

       [[3, 4]]])

* expands the dimension of the array with number as axis. eg: [1,2],[3,4]----2 axis hence 2d

In [90]:
#69 - eye
np.eye(3,4,0,dtype=float)                         # a 3x4 matrix containing zeros except for the 0th diagonal that contains ones

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [91]:
np.eye(3,4,1,dtype=float)          

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [92]:
#70 - fft

signal = np.array([-2., 8., -6., 4., 1., 0., 3., 5.])                        # could also be complex
fourier = np.fft.fft(signal)
fourier

array([ 13.         +0.j        ,   3.36396103 +4.05025253j,
         2.         +1.j        ,  -9.36396103-13.94974747j,
       -21.         +0.j        ,  -9.36396103+13.94974747j,
         2.         -1.j        ,   3.36396103 -4.05025253j])

* Compute the one-dimensional discrete Fourier Transform.

In [93]:
#71 - fftfreq
signal = np.array([-2., 8., -6., 4., 1., 0., 3., 5.])
fourier = np.fft.fft(signal)
N = len(signal)
timestep = 0.1                                  # if unit=day -> freq unit=cycles/day
freq = np.fft.fftfreq(N, d=timestep)                   # freqs corresponding to 'fourier'
freq


array([ 0.  ,  1.25,  2.5 ,  3.75, -5.  , -3.75, -2.5 , -1.25])

* The returned float array f contains the frequency bin centers in cycles per unit of the sample spacing (with zero at the start)

In [94]:
#72 - fftfreq
freq = np.fft.fftshift(freq)                       # freqs in ascending order
freq

array([-5.  , -3.75, -2.5 , -1.25,  0.  ,  1.25,  2.5 ,  3.75])

* Shift the zero-frequency component to the center of the spectrum

In [95]:
#73 - fill
a = np.arange(4, dtype=float)
print(a)
    
a.fill(7)                             # replace all elements with the number 7
print(a)

a.fill(6.5)                          # fill value is converted to dtype of a
a

[0. 1. 2. 3.]
[7. 7. 7. 7.]


array([6.5, 6.5, 6.5, 6.5])

* fill the array with the given value and dtype

In [96]:
#74 - finfo
f = np.finfo(float)                          # the numbers given are machine dependent
f.nmant, f.nexp                           # nr of bits in the mantissa and in the exponent

(52, 11)

* Machine limits for floating point types.

In [97]:
#75 - fix
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7,99.6])
np.fix(a)                                                  # round a to nearest integer towards zero

array([-1., -1., -0.,  0.,  1.,  1., 99.])

* round a to nearest integer towards zero

In [98]:
#76 - flat
a = np.array([[10,30],[40,60]])
iter = a.flat()                            # .flat returns an iterator
np.iter.next(a)                               # cycle through array with .next()

TypeError: 'numpy.flatiter' object is not callable

* used as a 1_D iterator over N-dimensional arrays. It is not a subclass 

In [106]:
#77 - flatten
a = np.array([[[1,2]],[[3,4]]])
print(a)

b = a.flatten()                       # b is now a 1-d version of a, a new array, not a reference
print(b)

[[[1 2]]

 [[3 4]]]
[1 2 3 4]


* Return a copy of the array converts into one dimension.

In [107]:
#78 - fliplr
a = np.arange(12).reshape(4,3)
print(a)

np.fliplr(a)                                    # flip left-right

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

* flip the element left-right along axis=1

In [108]:
#79 - flipud
a = np.arange(12).reshape(4,3)
print(a)

np.flipud(a)                                    # flip up-down

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

* flip the element up-down along axis=0

In [109]:
#80 - floor
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])
np.floor(a)                                      # nearest integer smaller-than or equal to a

array([-2., -2., -1.,  0.,  1.,  1.])

* nearest integer smaller-than or equal to a

In [110]:
#81 - fromarrays
x = np.array(['Smith','Johnson','McDonald'])                        # datatype is string
y = np.array(['F','F','M'], dtype='S1')                             # datatype is a single character
z = np.array([20,25,23])                                            # datatype is integer
data = np.rec.fromarrays([x,y,z], names='surname, gender, age')        # convert to record array
data[1]

('Johnson', b'F', 25)

* Create a record array from a (flat) list of arrays

In [111]:
#82 - frombuffer
buffer = b"\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08\
          @\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@"
#A=buffer.encode()
a = np.frombuffer(A, dtype = np.uint8)
a

array([  0,   0,   0,   0,   0,   0, 240,  63,   0,   0,   0,   0,   0,
         0,   0,  64,   0,   0,   0,   0,   0,   0,   8,  64,   0,   0,
         0,   0,   0,   0,  16,  64], dtype=uint8)

In [112]:
#83 - fromfile
y = np.array([2.,4.,6.,8.])
y.tofile("myfile.dat")                                     # binary format
y.tofile("myfile.txt", sep='\n', format = "%e")            # ascii format, one column, exponential notation
np.fromfile('myfile.dat', dtype=float)

array([2., 4., 6., 8.])

* tofile-allows you to save an array to a text or binary file. 
* fromfile-This will discuss saving and reading a NumPy array to and from a binary file.

In [113]:
#84 - fromfunction
def f(i,j):
    return i**2 + j**2
np.fromfunction(f, (3,3))                    # evaluate functiom for all combinations of indices [0,1,2]x[0,1,2]

array([[0., 1., 4.],
       [1., 2., 5.],
       [4., 5., 8.]])

* constructs an array by executing a function over each coordinate.

In [114]:
#95 - generic
numpyscalar = np.string_('7')                    # Convert to numpy scalar
numpyscalar                                    # Looks like a build-in scalar...

type(numpyscalar)                             # ... but it isn't

buildinscalar = '7'                              # Build-in python scalar
type(buildinscalar)

print(isinstance(numpyscalar, np.generic))              # Check if scalar is a NumPy one
            
isinstance(buildinscalar, np.generic)                      # Example on how to recognize NumPy scalars


True


False

In [115]:
#96 - gumbel
np.random.gumbel(loc=0.0,scale=1.0,size=(2,3))                 # Gumbel distribution location=0.0, scale=1.0

array([[-0.26261687,  1.64019647,  0.28423643],
       [ 0.688672  ,  1.6799589 , -0.53089902]])

* Draw samples from a Gumbel distribution with specified location and scale.
* the Gumbel distribution is used to analyze such variables as monthly and annual maximum values of daily rainfall and river discharge volumes, and also to describe droughts.
* location parameter and scale parameter. The case where location = 0 and scale = 1 is called the standard Gumbel distribution.

In [116]:
#97 - histogram
x = np.array([0.2, 6.4, 3.0, 1.6, 0.9, 2.3, 1.6, 5.7, 8.5, 4.0, 12.8])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])                                # increasing monotonically
N,bins = np.histogram(x,bins)
N,bins


(array([2, 3, 1, 4], dtype=int64), array([ 0. ,  1. ,  2.5,  4. , 10. ]))

* The Numpy histogram function is similar to the hist() function of matplotlib library, the only difference is that the Numpy histogram gives the numerical representation of the dataset while the hist() gives graphical representation of the dataset.
*  function which represents the frequency of data distribution in the graphical form.

In [117]:
#98 - hsplit
a = np.array([[1,2,3,4],[5,6,7,8]])
np.hsplit(a,2)                                     # split, column-wise, in 2 equal parts

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [118]:
#99 - hstack
a =np.array([[1],[2]])                      # 2x1 array
b = np.array([[3,4],[5,6]])                 # 2x2 array
np.hstack((a,b,a))                          # only the 2nd dimension of the arrays is allowed to be different

array([[1, 3, 4, 1],
       [2, 5, 6, 2]])

* function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.


In [119]:
#100 - hypot
np.hypot(3.,4.)                    # hypotenuse: sqrt(3**2 + 4**2) = 5

5.0

In [120]:
z = np.array([2+3j, 3+4j])
np.hypot(z.real, z.imag)                        # norm of complex numbers

array([3.60555128, 5.        ])

* sqrt(x1 ** 2 + x2 ** 2)``, element-wise
