In [1]:
import numpy as np
from numpy import random 

In [2]:
#101 - identity()
np.identity(3,np.float)

C:\Users\DELL\AppData\Local\Temp\ipykernel_5296\2965622267.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.identity(3,np.float)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* Return the identity matrix

In [6]:
#102 - ifft()
signal = np.array([-2., 8., -6., 4., 1., 0., 3., 5.])
fourier = np.fft.fft(signal)
np.fft.ifft(fourier)                                                 # Inverse fourier transform

array([-2.00000000e+00+0.j,  8.00000000e+00+0.j, -6.00000000e+00+0.j,
        4.00000000e+00+0.j,  1.00000000e+00+0.j, -1.77635684e-15+0.j,
        3.00000000e+00+0.j,  5.00000000e+00+0.j])

* Compute the one-dimensional inverse discrete Fourier Transform

In [9]:
#103 - imag()
a = np.array([1+2j,3+4j,5+6j])
print(a.imag)                                   # display imag value

a.imag = 9                                # replace imag value with 9
print(a)                               

[2. 4. 6.]
[1.+9.j 3.+9.j 5.+9.j]


* Return the imaginary part of the complex argument.

In [10]:
#104 - index_exp[]
myslice = np.index_exp[2:4,...,4,::-1]                             # myslice could now be passed to a function, for example.
print(myslice)

(slice(2, 4, None), Ellipsis, 4, slice(None, None, -1))


* The exp function in NumPy is used to compute the exponent of all values present in the given array. 

In [12]:
#105 - indices
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

* Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [25]:
#106 - inf
x = np.array([2,1,np.inf])                      # inf = infinite = number too large to represent, machine dependent
print(np.isfinite(x))                            # show which elements are not nan/inf/-inf - finite values
np.isinf(x)                                       # show which elements are inf/-inf -  infinite avlues

[ True  True False]


array([False, False,  True])

* returns a boolean value if the value is positive or negative infinity

In [24]:
#107 - inner
x = np.array([1,2,3])
y = np.array([10,20,30])
np.inner(x,y)                                      # 1x10+2x20+3x30 = 140
  

140

* sum of products of 2 arrays

In [26]:
#108 - insert
a = np.array([10,20,30,40])
np.insert(a,[1,3],50)                              # insert value 50 before elements [1] and [3]


array([10, 50, 20, 30, 50, 40])

* Insert values along the given axis before the given indices.

In [30]:
#109 - inv
a = np.array([[3,1,5],[1,0,8],[2,1,4]])
print(a)
inva = np.linalg.inv(a)                                        # Inverse matrix
print(inva)

[[3 1 5]
 [1 0 8]
 [2 1 4]]
[[ 1.14285714 -0.14285714 -1.14285714]
 [-1.71428571 -0.28571429  2.71428571]
 [-0.14285714  0.14285714  0.14285714]]


* Compute the (multiplicative) inverse of a matrix.
*  numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [31]:
#110 - iscomplex
a = np.array([1,2,3.j])
np.iscomplex(a)

array([False, False,  True])

* Returns a bool array, where True if input element is complex.

In [32]:
#111 - iscomplexobj
a = np.array([1,2,3.j])
np.iscomplexobj(a)

True

* return true if atleast one element in the array is a complex number

In [34]:
#112 - item
a = np.array([5])
print(type(a.item()))

b = np.array([2,3,4])
b[1].item()                           # Conversion of 2nd element to Python scalar

<class 'int'>


3

* item() - converts an element of array to standard pyhton scalar


In [37]:
#113 - ix_
a = np.arange(9).reshape(3,3)
print(a)

indices = np.ix_([0,1,2],[1,2,0])                  # trick to be used with array broadcasting
print(indices)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([[0],
       [1],
       [2]]), array([[1, 2, 0]]))


*  construct an open mesh from multiple sequences. This function takes N 1-D sequences and returns N outputs with N dimensions each, such that the shape is 1 in all but one dimension and the dimension with the non-unit shape value cycles through all N dimensions

In [38]:
#114 - lexsort
serialnr = np.array([1023, 5202, 6230, 1671, 1682, 5241])
height = np.array([40., 42., 60., 60., 98., 40.])
width = np.array([50., 20., 70., 60., 15., 30.])

# We want to sort the serial numbers with increasing height, _AND_
# serial numbers with equal heights should be sorted with increasing width.

indices = np.lexsort(keys = (width, height))                                     # mind the order!
indices

array([5, 0, 1, 3, 2, 4], dtype=int64)

* return the index of elements of serial number according to sorting of elements in the height,serial numbers with equal heights should be sorted with increasing width.

In [41]:
#115 - linspace
np.linspace(0,5,num=10)                                     # 6 evenly spaced numbers between 0 and 5 incl.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

* return the total of elements 10 in an array between 0-5

In [51]:
#116 - loadtxt
data = np.loadtxt("myfile.txt")                        # myfile.txt contains 4 columns of numbers
t,z = data[:0], data[:3]                          # data is 2D numpy array
t,z

(array([], dtype=float64), array([2., 4., 6.]))

* Load data from a text file. Each row in the text file must have the same number of values.

In [53]:
#117 - logical_and
np.logical_and(np.array([0,0,1,1]), np.array([0,1,0,1]))

array([False, False, False,  True])

* Compute the truth value(1&1) of x1 AND x2 element-wise

In [55]:
#118 - logical_not
np.logical_not(np.array([0,1]))
np.logical_not(np.array([False,True]))

array([ True, False])

* Compute the truth value of NOT x element-wise.

In [56]:
#119 - logical_or
np.logical_or(np.array([0,0,1,1]), np.array([0,1,0,1]))

array([False,  True,  True,  True])

* Compute the truth value(atleast one true is true) of x1 OR x2 element-wise

In [58]:
#120 - logical_xor
np.logical_xor(np.array([0,0,1,1]), np.array([0,1,0,1]))

array([False,  True,  True, False])

In [60]:
#121 - logspace
np.logspace(-2, 3, num = 7)                          # 6 evenly spaced pts on a logarithmic scale, from 10^{-2} to 10^3 incl

array([1.00000000e-02, 6.81292069e-02, 4.64158883e-01, 3.16227766e+00,
       2.15443469e+01, 1.46779927e+02, 1.00000000e+03])

* return the total of elements 7 in an array between 10^{-2} to 10^3

In [62]:
#123,124- mat,matrix
A=np.mat('1 3 4; 5 6 9')                                # matrices are always 2-dimensional
print(A)

a = np.array([[1,2],[3,4]])
m = np.mat(a)                            # convert 2-d array to matrix
m

[[1 3 4]
 [5 6 9]]


matrix([[1, 2],
        [3, 4]])

* Interpret the input as a matrix.


In [63]:
#125,126 - max,maximum
a = np.array([1,0,5])
b = np.array([3,2,4])
np.maximum(a,b)                              # element-by-element comparison

array([3, 2, 5])

* returns the maximum value from 2 array, element wise

In [65]:
#126 - nan
x = np.array([2, np.nan, 1])
np.isnan(x)                                    # show which elements are nan
 

array([False,  True, False])

* returns boolean, true for nan 

In [72]:
#127 - ndenumerate
a = np.arange(9).reshape(3,3) + 10
print(a)

b = np.ndenumerate(a)
for position,value in b: 
    print(position,value)                           # position is the N-dimensional index

[[10 11 12]
 [13 14 15]
 [16 17 18]]
(0, 0) 10
(0, 1) 11
(0, 2) 12
(1, 0) 13
(1, 1) 14
(1, 2) 15
(2, 0) 16
(2, 1) 17
(2, 2) 18


* Return an iterator yielding pairs of array coordinates(index) and values

In [75]:
#128 - ndim
a =np.arange(12).reshape(3,4)
np.ndim(a)

2

* Return the number of dimensions of an array

In [78]:
#129 - ndindex
for index in np.ndindex(4,3,2):
        print(index)

(0, 0, 0)
(0, 0, 1)
(0, 1, 0)
(0, 1, 1)
(0, 2, 0)
(0, 2, 1)
(1, 0, 0)
(1, 0, 1)
(1, 1, 0)
(1, 1, 1)
(1, 2, 0)
(1, 2, 1)
(2, 0, 0)
(2, 0, 1)
(2, 1, 0)
(2, 1, 1)
(2, 2, 0)
(2, 2, 1)
(3, 0, 0)
(3, 0, 1)
(3, 1, 0)
(3, 1, 1)
(3, 2, 0)
(3, 2, 1)


* np.ndindex() routine provides us an iterator that returns the indices of elements in an N-dimensional array

In [83]:
#130 - newaxis
x = np.arange(3)
print(x)
print(x[:,np.newaxis])                                      # add a new dimension/axis
x[:,np.newaxis,np.newaxis]                                  # add two new dimensions/axes

[0 1 2]
[[0]
 [1]
 [2]]


array([[[0]],

       [[1]],

       [[2]]])

*  is used to increase the dimension of the existing array by one more dimension, when used once

In [84]:
#131 - nonzero
x = np.array([1,0,2,-1,0,0,8])
indices = np.nonzero(x)                                      # find the indices of the nonzero elements
indices

(array([0, 2, 3, 6], dtype=int64),)

* rturn the index of the non zero element 

In [86]:
#132 - ogrid
x,y = np.ogrid[0:3,0:3]                               # x and y are useful to use with broadcasting rules
x

array([[0],
       [1],
       [2]])

In [87]:
y

array([[0, 1, 2]])

* NumPy ogrid is one of its functions that stands for the open grid. It helps us by providing a way to act on a particular pixel of an image.
*  returns an open multi-dimensional “meshgrid

In [88]:
#133 - mean
a = np.array([1,2,7])
a.mean()

3.3333333333333335

* average of the elements

In [89]:
#134 - median
a = np.array([1,2,3,4,9])
np.median(a)

3.0

* evaluates median of the array

In [92]:
#135 - mgrid
m = np.mgrid[1:3,2:5]                                 # rectangular mesh grid with x-values [1,2] and y-values [2,3,4]
print(m)

[[[1 1 1]
  [2 2 2]]

 [[2 3 4]
  [2 3 4]]]


* returns a dense multi-dimensional "meshgrid

In [93]:
#135 - min
a = np.array([[10,50,30],[60,20,40]])
a.min()

10

* min value in the array

In [97]:
#135 - minimum
a = np.array([1,0,5])
b = np.array([3,2,4])
np.minimum(a,b)                                 # element-by-element comparison

array([1, 0, 4])

* returns the minimum value from 2 array, element wise

In [98]:
#136 - multiply
np.multiply(np.array([3,6]), np.array([4,7]))

array([12, 42])

* Multiply arguments element-wise

In [99]:
#141 - ones_like
a = np.array([[1,2,3],[4,5,6]])
np.ones_like(a)                         # ones initialised array with the same shape and datatype as 'a'

array([[1, 1, 1],
       [1, 1, 1]])

* Return an array of ones with the same shape and type as a given input array

In [100]:
#142 - outer
x = np.array([1,2,3])
y = np.array([10,20,30])
np.outer(x,y)                                               # outer product

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

* compute the outer level of products like vectors, arrays, etc.

In [104]:
#143 - permutation
np.random.permutation(4)                               # permutation of integers from 0 to 3

array([1, 2, 0, 3])

* return a permuted range

In [107]:
#144 - piecewise
f1 = lambda x: x*x
f2 = lambda x: 2*x
x = np.arange(-2.,3.,0.1)
condition = (x>1)&(x<2)                                                   # boolean array
y = np.piecewise(x,condition, [f1,1.])                                       # if condition is true, return f1, otherwise 1.
y = np.piecewise(x, np.fabs(x)<=1, [f1,0]) + np.piecewise(x, x>1, [f2,0])          # 0. in ]-inf,-1[, f1 in [-1,+1], f2 in ]+1,+inf[
print(y)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.00000000e+00 8.10000000e-01
 6.40000000e-01 4.90000000e-01 3.60000000e-01 2.50000000e-01
 1.60000000e-01 9.00000000e-02 4.00000000e-02 1.00000000e-02
 3.15544362e-30 1.00000000e-02 4.00000000e-02 9.00000000e-02
 1.60000000e-01 2.50000000e-01 3.60000000e-01 4.90000000e-01
 6.40000000e-01 8.10000000e-01 2.00000000e+00 2.20000000e+00
 2.40000000e+00 2.60000000e+00 2.80000000e+00 3.00000000e+00
 3.20000000e+00 3.40000000e+00 3.60000000e+00 3.80000000e+00
 4.00000000e+00 4.20000000e+00 4.40000000e+00 4.60000000e+00
 4.80000000e+00 5.00000000e+00 5.20000000e+00 5.40000000e+00
 5.60000000e+00 5.80000000e+00]


* Given a set of conditions and corresponding functions, evaluate each
function on the input data wherever its condition is true.


In [109]:
#145 - pinv
A = np.array([[1., 3., 5.],[2., 4., 6.]])
b = np.array([1., 3.])

# Question: find x such that ||A*x-b|| is minimal
# Answer: x = pinvA * b, with pinvA the pseudo-inverse of A

pinvA = np.linalg.pinv(A)
print(pinvA)

[[-1.33333333  1.08333333]
 [-0.33333333  0.33333333]
 [ 0.66666667 -0.41666667]]


* Compute the pseudo-inverse of a matrix.

In [113]:
#146 - poisson
np.random.poisson(lam=0.5, size=(2,3))                  # poisson distribution lambda=0.5

array([[1, 0, 0],
       [0, 2, 0]])

* Draw samples from a Poisson distribution.
* The Poisson distribution is the limit of the binomial distribution
for large N

In [114]:
#147 - poly1d
p1 = np.poly1d([2,3],r=1)                           # specify polynomial by its roots
p1

poly1d([ 1., -5.,  6.])

* returns the polynomial by its roots([2,3])

In [117]:
#148 - polyfit
x = np.array([1,2,3,4,5])
y = np.array([6, 11, 18, 27, 38])
np.polyfit(x,y,2)                           # fit a 2nd degree polynomial to the data, result is x**2 + 2x + 3

array([1., 2., 3.])

* least squares polynomial fit.

In [118]:
#149 - prod
a = np.array([1,2,3])
a.prod()                                                # 1 * 2 * 3 = 6

6

* Return the product of the array elements over the given axis

In [119]:
#150 - ptp
a = np.array([5,15,25])
a.ptp()                                                 # peak-to-peak = maximum - minimum

20

* Peak to peak (maximum - minimum) value along a given axis.

In [122]:
#151 - put
a = np.array([10,20,30,40])
a.put([0,3,2],[60,70,80])                               # first indices, then values
a

array([60, 20, 80, 70])

* replace the elements with new elements along the given indeices 

In [127]:
#152 - putmask
a = np.array([10,20,30,40])
mask = np.array([True,False,True,True])                # size mask = size a
np.putmask(a,[60,70,80,90], mask)                      # first values, then the mask
a

array([1, 0, 1, 1])

* Changes elements of an array based on conditional and input values.


In [128]:
#153 - r_[]
np.r_[1:5]                                             # same as arange(1,5)

array([1, 2, 3, 4])

In [129]:
np.r_[1:10:4]                                          # same as arange(1,10,4)

array([1, 5, 9])

* Translates slice objects to concatenation along the first axis.

In [133]:
#154 - rand
np.random.rand(3,2)

array([[0.79841733, 0.55053661],
       [0.67583164, 0.08721136],
       [0.13388783, 0.90194768]])

* Random values in a given shape.

In [137]:
#155,156 - randint,random_integers
np.random.random_integers(-1,5,(2,2))

C:\Users\DELL\AppData\Local\Temp\ipykernel_5296\2334570622.py:2: DeprecationWarning: This function is deprecated. Please call randint(-1, 5 + 1) instead
  np.random.random_integers(-1,5,(2,2))


array([[ 4,  1],
       [-1,  0]])

* Return random integers of type `np.int_` from the "discrete uniform" distribution in the closed interval [`low`, `high`]

In [138]:
# 157 - randn
np.random.randn(2,3)

array([[ 0.34126588, -0.97846872,  1.24891599],
       [-0.03951925,  0.96081188,  0.01218355]])

* Return a sample (or samples) from the "standard normal" distribution.

In [163]:
# 158,159,171 - random_sample,ranf,sample
np.random.random_sample((3,2))

array([[0.81934079, 0.02750174],
       [0.0934604 , 0.07019454],
       [0.64444934, 0.09014949]])

* Return random floats in the half-open interval [0.0, 1.0]. Results are from the "continuous uniform" distribution over the
stated interval. 

In [141]:
# 160 - ravel
a = np.array([[1,2],[3,4]])
a.ravel()                                       # 1-d version of a

array([1, 2, 3, 4])

* Return a flattened(1-d) array.

In [142]:
# 161 - real
a = np.array([1+2j,3+4j,5+6j])
a.real

array([1., 3., 5.])

* returns the real part of the complex number

In [144]:
# 162 - recarray
num = 2
a = np.recarray(num, formats='i4,f8,f8',names='id,x,y')
a['id'] = [3,4]
a['id']
a

rec.array([(3, 5.29980882e-315, 5.30498948e-315),
           (4, 4.00000000e+000, 5.00000000e+000)],
          dtype=[('id', '<i4'), ('x', '<f8'), ('y', '<f8')])

* Construct an ndarray that allows field access using attributes.

 * Arrays may have a data-types containing fields, analogous
to columns in a spread sheet.

In [145]:
# 163 - reduce
np.add.reduce(np.array([1.,2.,3.,4.]))                                   # computes ((((1.)+2.)+3.)+4.)

10.0

*  A reducing function takes a collection of values and calculates a single representative value.

In [146]:
# 164 - repeat
np.repeat(7., 4)                                # repeats 7 for 4 times

array([7., 7., 7., 7.])

In [147]:
a = np.array([10,20])
a.repeat([3,2])

array([10, 10, 10, 20, 20])

* Repeat elements of an array.

In [148]:
# 165 - reshape
x = np.arange(12)
x.reshape(3,4)                       # array with 3 rows and 4 columns. 3x4=12. Total number of elements is always the same.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

* Returns an array containing the same data with a new shape.

In [157]:
# 166 - resize
a = np.array([1,2,3,4])
a.resize(2,2)                          # changes shape of 'a' itself
print(a)

[[1 2]
 [3 4]]


* Change shape and size of array in-place.

In [156]:
# 167 - rollaxis
a = np.arange(3*4*5).reshape(3,4,5)
print(a.shape)

b = np.rollaxis(a,1,0)                                # transpose array so that axis 1 is 'rolled' before axis 0
b.shape

(3, 4, 5)


(4, 3, 5)

* Roll the specified axis backwards, until it lies in a given position.

In [158]:
# 168 - round
np. array([1.2345, -1.647]).round()                   # rounds the items. Type remains float64.

array([ 1., -2.])

* round the elements to integers

In [161]:
# 169 - rot90
a = np.arange(12).reshape(4,3)
print(a)

np.rot90(a)                                                 # 'rotate' the matrix 90 degrees

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 2,  5,  8, 11],
       [ 1,  4,  7, 10],
       [ 0,  3,  6,  9]])

* Rotate an array by 90 degrees in the plane specified by axes.

In [162]:
# 170 - s_[]
np.s_[1:5]                                                 # easy slice generating. See r_[] examples.

slice(1, 5, None)

In [165]:
# 172 - savetxt
data = np.arange(12).reshape(4,3)
np.savetxt("myfile.txt", data)                                 # data is 2D array
y.tofile("myfile.date")

* Save an array to a text file.

In [169]:
# 173 - searchsorted
a = np.array([1,2,2,3])                               # a is 1-D and in ascending order.
a.searchsorted(2.5)                                    # side defaults to "left"                         

3

* returns the index where the specified element is to be inserted in 'a' to maintain order

In [172]:
# 174 - seed
np.random.seed([1])                          # seed the pseudo-random number generator
np.random.rand(3)

array([0.13436424, 0.84743374, 0.76377462])

*  numerical value that generates a new set or repeats pseudo-random numbers

In [174]:
# 175 - select
x = np.array([5., -2., 1., 0., 4., -1., 3., 10.])
np.select([x < 0, x == 0, x <= 5], [x-0.1, 0.0, x+0.2], default = 100.)

array([  5.2,  -2.1,   1.2,   0. ,   4.2,  -1.1,   3.2, 100. ])

* Return an array drawn from elements in choicelist, depending on conditions.

In [178]:
# 176 - set_printoptions
x = np.array([np.pi, 1.e-200])
x

np.set_printoptions(precision=3, suppress=True)                    # 3 digits behind decimal point + suppress small values
x

array([3.142, 0.   ])

* compute the values of arguements in a array
* precision=3 - 3 digits behind decimal point
* suppress=True - suppress small values

In [179]:
# 177 - shape
x = np.arange(12)
x.shape

(12,)

In [180]:
x.shape = (3,4)              # array with 3 rows and 4 columns. 3x4=12. Total number of elements is always the same.
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

* returns number of rows and columns

In [185]:
# 178 - shuffle
x = np.array([1,50,-1,3])
np.random.shuffle(x)                                # shuffle the elements of x
print(x)

[50  3 -1  1]


* shuffle the elements of x.  This function only shuffles the array along the first axis of a multi-dimensional array.

In [191]:
# 179 - slice
a = np.arange(20)
print(a)
a[3:9:2]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([3, 5, 7])

In [195]:
# 180 - solve

# The system of equations we want to solve for (x0,x1,x2):
# 3 * x0 + 1 * x1 + 5 * x2 = 6
# 1 * x0 + 8 * x2 = 7
# 2 * x0 + 1 * x1 + 4 * x2 = 8

a = np.array([[3,1,5],[1,0,8],[2,1,4]])
b = np.array([6,7,8])
x = np.linalg.solve(a,b)
print(x)                                                     # This is our solution

[-3.286  9.429  1.286]


In [198]:
# 181 - sometrue
b = np.array([False, False, False, True])
np.sometrue(b)

True

* returns a boolean for atleast one true

In [199]:
# 182 - sort
a = np.array([2,0,8,4,1])
a.sort()                                  # in-place sorting with quicksort (default)
a

array([0, 1, 2, 4, 8])

* ascending order of elements in array

* Split an array into multiple sub-arrays as per given `ary`

In [200]:
# 183 - split
a = np.array([[1,2,3,4],[5,6,7,8]])
np.split(a,2,axis=0)                                       # split a in 2 parts. row-wise

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [202]:
# 184 - squeeze
a = np.arange(6)
a = a.reshape(1,2,1,1,3,1)
print(a)

a.squeeze()                                            # result has shape 2x3, all dimensions with length 1 are removed

[[[[[[0]
     [1]
     [2]]]]



  [[[[3]
     [4]
     [5]]]]]]


array([[0, 1, 2],
       [3, 4, 5]])

* This function removes one-dimensional entry from the shape of the given array. Two parameters are required for this function.

In [203]:
# 185 - std
a = np.array([1.,2,7])
a.std()                                      # normalized by N (not N-1)

2.6246692913372702

* Returns the standard deviation of the array elements along given axis.

In [207]:
# 186 - standard_normal
np.random.standard_normal((2,3))

array([[ 0.393,  1.3  , -0.304],
       [-0.663,  0.215,  1.761]])

* Return a sample (or samples) from the "standard normal" distribution.

In [208]:
# 187 - sum
a = np.array([1,2,3])
a.sum()

6

* Return the sum of the array elements over the given axis

In [212]:
# 188 - svd
A = np.array([[1., 3., 5.],[2., 4., 6.]])            # A is a (2x3) matrix
U,sigma,V = np.linalg .svd(A)
print(U)                                         # U is a (2x2) unitary matrix

[[-0.62   0.785]
 [-0.785 -0.62 ]]


* svd() function is used to compute the factor of an array by Singular Value Decomposition.
* Singular Value Decomposition, or SVD, has a wide array of applications. These include dimensionality reduction, image compression, and denoising data.

In [213]:
# 189 - swapaxes
a = np.arange(30)
a = a.reshape(2,3,5)
print(a)

b = a.swapaxes(1,2)                            # swap the 2nd and the 3rd axis
b

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


array([[[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]],

       [[15, 20, 25],
        [16, 21, 26],
        [17, 22, 27],
        [18, 23, 28],
        [19, 24, 29]]])

* tranforms rows into columns and columns into rows

In [214]:
# 190 - T
x = np.array([[1.,2.],[3.,4.]])
print(x)

x.T                                          # shortcut for transpose()

[[1. 2.]
 [3. 4.]]


array([[1., 3.],
       [2., 4.]])

* transpose of x (tranforms rows into columns and columns into rows)

In [215]:
# 191 - take
a= np.array([10,20,30,40])
a.take([0,0,3])                                    # [0,0,3] is a set of indices

array([10, 10, 40])

* return the array with specified index of elements from 'a' 

In [217]:
# 192 - tensordot
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))           # sum over the 1st and 2nd dimensions
c.shape

(5, 2)

* Compute tensor dot product along specified axes
* Tensordot (also known as tensor contraction) sums the product of elements from a and b over the indices specified by axes

In [218]:
# 193 - tile
a = np.array([10,20])
np.tile(a, (3,2))                                     # concatenate 3x2 copies of a together

array([[10, 20, 10, 20],
       [10, 20, 10, 20],
       [10, 20, 10, 20]])

* Construct an array by repeating 'a' the number of times given by reps.

In [220]:
# 194 - tofile
x = np.arange(10.)
y = x**2
y.tofile("myfile.dat")                                # binary format

* Write array to a file as text or binary (default).

In [221]:
# 195 - tolist
a = np.array([[1,2],[3,4]])
a.tolist()                                          # convert to a standard python list

[[1, 2], [3, 4]]

* Return a copy of the array data as a (nested) Python list.

In [224]:
# 196 - trace
a = np.arange(12).reshape(3,4)
print(a)

print(a.diagonal())

a.trace()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  5 10]


15

* returns sum of the diagonal of an array

In [227]:
# 197 - transpose
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.transpose()
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


* transpose of x (tranforms rows into columns and columns into rows)

In [231]:
# 198 - tri
np.tri(3,4,k=0,dtype=float)         # 3x4 matrix of Floats, triangular, the k=0-th diagonal and below is 1, the upper part is 0

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

* An array with ones at and below the given diagonal and zeros elsewhere.

In [234]:
# 199 - tril
a = np.arange(10,100,10).reshape(3,3)
print(a)
np.tril(a,k=0)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[10,  0,  0],
       [40, 50,  0],
       [70, 80, 90]])

* returns a Lower triangle of an array.

In [235]:
# 200 - triu
a = np.arange(10,100,10).reshape(3,3)
print(a)
np.triu(a,k=0)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[10, 20, 30],
       [ 0, 50, 60],
       [ 0,  0, 90]])

* returns a Lower triangle of an array.

In [238]:
# 201 - trim_zeros
x = np.array([0, 0, 0, 1, 2, 3, 0, 0])                     
np.trim_zeros(x,'f')                                 # f indicates remove zeros at the front,bf - back and front, b - back

array([1, 2, 3, 0, 0])

* remove zeroes from a 1-D array or sequence.

In [239]:
# 202 - typeDict
np.typeDict['short']

C:\Users\DELL\AppData\Local\Temp\ipykernel_5296\2459440874.py:2: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  np.typeDict['short']


numpy.int16

In [240]:
np.typeDict['uint16']

C:\Users\DELL\AppData\Local\Temp\ipykernel_5296\1891136687.py:1: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  np.typeDict['uint16']


numpy.uint16

In [244]:
# 203 - uniform
np.random.uniform(low=0,high=10,size=(2,3))                                 # uniform numbers in range [0,10)

array([[9.522, 9.265, 4.162],
       [9.163, 9.222, 1.   ]])

* Draw samples from a uniform distribution.
* uniform distribution refers to a type of probability distribution in which all outcomes are equally likely

In [243]:
# 204 - unique
x = np.array([2,3,2,1,0,3,4,0])
np.unique(x)                                                   # remove double values

array([0, 1, 2, 3, 4])

* returns only unique/distinct categories or values

In [252]:
# 206 - vander
x = np.array([1,2,3,5])
N=3
np.vander(x,N)                                                # Vandermonde matrix of the vector x

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

* Generate a Vandermonde matrix.
* Vandermonde, is a matrix with the terms of a geometric progression in each row:

In [253]:
# 207 - var
a = np.array([1,2,7])
a.var()                                 # normalised with N (not N-1)

6.888888888888888

* Returns the variance of the array elements, along given axis.

In [255]:
# 208 - vdot
x = np.array([1+2j,3+4j])
y = np.array([5+6j,7+8j])
np.vdot(x,y)                                            # conj(x) * y = (1-2j)*(5+6j)+(3-4j)*(7+8j)

(70-8j)

* Return the dot product of two vectors.

In [257]:
# 209 - vectorize
def myfunc(x):
    if x >= 0: 
        return x**2 
    else: 
        return -x

myfunc(2.)                                               # works fine


4.0

In [262]:
vecfunc = np.vectorize(myfunc, otypes=[float])         # declare the return type as float
vecfunc(np.array([-2,2]))                              # works fine!

array([2., 4.])

* Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently.

In [265]:
# 210 - view
a = np.array([1., 2.])
print(a.view())                                            # new array referring to the same data as 'a'

a.view(complex)                                     # pretend that a is made up of complex numbers


[1. 2.]


array([1.+2.j])

* new array with new data type with same data as 'a'

In [269]:
# 211 - vonmises
np.random.vonmises(mu=1,kappa=1,size=(2,3))           # Von Mises distribution mean=1.0, kappa=1

array([[-0.272, -2.314,  0.076],
       [ 0.097, -3.041,  0.312]])

* Samples are drawn from a von Mises distribution with specified mode
(mu) and dispersion (kappa), on the interval [-pi, pi].

* The von Mises distribution (also known as the circular normal
distribution) is a continuous probability distribution on the unit
circle.  It may be thought of as the circular analogue of the normal
distribution.


In [274]:
# 212 - vsplit
a = np.array([[1,2],[3,4],[5,6],[7,8]])
np.vsplit(a,2)                                             # split, row-wise, in 2 equal parts

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

* Split an array into multiple sub-arrays vertically (row-wise).

In [275]:
# 213 - vstack
a = np.array([1,2])
b = np.array([[3,4],[5,6]])
np.vstack((a,b,a))                                # only the first dimension of the arrays is allowed to be different

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2]])

* Stack arrays in sequence vertically (row wise).

In [277]:
# 214 - weibull
np.random.weibull(a=1,size=(2,3))                                 # I think a is the shape parameter

array([[2.143, 1.495, 1.34 ],
       [0.09 , 1.09 , 0.114]])

* Draw samples from a 1-parameter Weibull distribution with the given
shape parameter `a`.

In [278]:
# 215 - where
a = np.array([3,5,7,9])
b = np.array([10,20,30,40])
c = np.array([2,4,6,8])
np.where(a <= 6, b, c)

array([10, 20,  6,  8])

* Return elements chosen from `b` or `c` depending on `condition`.

In [279]:
# 216 - zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

* Return a new array of given shape and type, filled with zeros.

In [281]:
# 217 - zeros_like
a = np.array([[1,2,3],[4,5,6]])
np.zeros_like(a)                         # with zeros initialised array with the same shape and datatype as 'a'

array([[0, 0, 0],
       [0, 0, 0]])

* Return an array of zeros with the same shape and type as a given array.
